#!/bin/sh -e
#
# /etc/init.d/scan_server: Start the scanning server.
#
### BEGIN INIT INFO
# Provides:	  scan_server
# Required-Start: $local_fs $syslog $remote_fs mini-httpd
# Required-Stop: $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Scanning Server
# Description: starts the scanning server and assigns privileges
### END INIT INFO

# Copied from existing scripts.
# Modified by : Eran <eran@over-here.org>

NAME=scan_server
PATH_BIN=/usr/local/sbin:/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/sbin/start_scan_server
PIDFILE=/var/run/$NAME.pid
DEFAULTS=/etc/default/$NAME
DESC="scanning server"

ENV="env -i LANG=C PATH=$PATH_BIN"

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

RET=0

[ -r "$DEFAULTS" ] && . "$DEFAULTS" || start_scanner_server=yes


check_daemon_enabled () {
    if [ "$start_scanner_server" = "yes" ] ; then
        return 0
    else
        log_warning_msg "Not starting $NAME, disabled via /etc/default/$NAME"
        return 1
    fi

}


case "$1" in
  start)
    if check_daemon_enabled ; then
				log_daemon_msg "Starting $DESC" "$NAME" 
				if start-stop-daemon --start --exec $DAEMON --chuid scannerd; then
            log_end_msg 0
        else
            log_end_msg 1
            RET=1
        fi
    fi
    ;;

  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    if start-stop-daemon --stop -n python -u scannerd --retry 30 ; then
        log_end_msg 0
    else
        log_end_msg 1
        RET=1
    fi
    ;;

  restart)
    if check_daemon_enabled ; then
        log_action_begin_msg "Restarting $NAME"
        if $0 stop && $0 start ; then
            log_action_end_msg 0
        else
            log_action_cont_msg "(failed)"
            RET=1
        fi
    fi
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    RET=1
    ;;
esac


exit $RET
